### ISSUE TITLE
Add about page

### ISSUE THREAD

**Issue by dagheyman** [Yubico/yubikey-manager-qt#1]
Should include copyright information , version number and maybe a link to knowledge base.

**Comment by SueHeim** [comment]
Required text:

YubiKey Manager
Version x.x.xx
(c) 2016, Yubico Inc. All rights reserved.

If we have a menu option for About, do we also have a menu option for Help? If so, then we can link to the yubico.com KB for a guide (would be great if we could create a help system but I think that may be out of scope right now).
