### ISSUE TITLE
App hangs on "Applications > OTP"

### ISSUE THREAD

**Issue by mennanov** [Yubico/yubikey-manager-qt#121]
If i go to "Applications -> OTP" the app hangs showing a loading bar.
It worked earlier though, not sure what caused this behavior, but i suspect that it happened after i configured GPG keys to be used for SSH (via `gpg --card-edit`).
I've tried to `killall gpg-agent`, but it did not help either. 

Not sure if it's related, but some other tools are now failing too: 
```
ykpamcfg -2 
USB error: kIOReturnSuccess
```

I've tried both security keys that i have (only one of them was used for GPG), all USB ports, nothing helps.

OS X 10.14.1
YubiKey Manager version = 1.0.1

**Comment by dagheyman** [comment]
Solved in referenced issue.
