### ISSUE TITLE
OATH-HOTP number of digits is ignored (always programs as 6)

### ISSUE THREAD

**Issue by samh** [Yubico/yubikey-manager-qt#131]
In the YubiKey Manager GUI (tested with 1.0.0 and 1.0.1 on Windows), selecting 8 digits when programming OATH-HOTP in an OTP slot will instead program as 6 digits.

Programming from the ykman CLI works as expected.

**Comment by dagheyman** [comment]
Thanks for the report! Confirmed this bug as well. Will be fixed in the next release.
