### ISSUE TITLE
Release tarballs are tar bombs

### ISSUE THREAD

**Issue by kbabioch** [Yubico/yubikey-manager-qt#155]
Since a couple of releases ago the release tarballs are tar bombs, i.e. they extract into the current workd directory instead of a subdir. In this regards `yubikey-manager-qt` behaves differently than any other YubiKey package (e.g. `yubikey-manager`) and it makes dealing with those archives more difficult than with any other product, since it overwrites files in the working directory and you cannot extract two version of this package without specifying additional arguments.

This should be changed back for future releases.

**Comment by dagheyman** [comment]
Thanks for pointing this out, will fix this for future releases.

**Comment by dagheyman** [comment]
Fixed for 1.1.1
