### ISSUE TITLE
Does not run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [Yubico/yubikey-manager-qt#167]
Thanks for providing an AppImage. However, it does not run on Ubuntu 14.04 which currently is the oldest still-supported Ubuntu release:

```
usr/bin/ykman-gui: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /run/firejail/appimage/.appimage-10337/usr/lib/libQt5QuickControls2.so.5)
```

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems.

Reference and test log at:
https://github.com/AppImage/appimage.github.io/pull/1324

**Comment by dagheyman** [comment]
Thanks, but Ubuntu 14.04 is end of life next month, so we will not prioritize fixing this.
