### ISSUE TITLE
Importing key gives "PIV unmapped error: null list index out of range"

### ISSUE THREAD

**Issue by keestux** [Yubico/yubikey-manager-qt#171]
When I want to import a private key I'm getting this error message.
```
qml: PIV unmapped error: null list index out of range
```

It turns out that `parse_certificates()` does not throw an exception, but it returns an empty list. The code in `piv_import_file` then still thinks that there are certs. And eventually it accesses `certs[0]` which causes the above error. The solution is simple, I'll send a PR shortly.

**Comment by dagheyman** [comment]
Thanks, this is fixed in HEAD in yubikey-manager, and will be fixed in the next release. Keeping issue open until release is out.

**Comment by dagheyman** [comment]
Fixed in 1.1.1
