### ISSUE TITLE
Fedora build

### ISSUE THREAD

**Issue by vorburger** [Yubico/yubikey-manager-qt#182]
I'm trying to build this project on Fedora 29, and (so far) failing...

https://github.com/Yubico/yubikey-manager-qt/compare/master...vorburger:docFedoraBuild has how far I got so far, and it currently fails with:

```
qmake-qt5 && make
cd ykman-gui/ && ( test -e Makefile || /usr/bin/qmake-qt5 -o Makefile /home/vorburger/dev/YubiKey/git/yubikey-manager-qt/ykman-gui/ykman-gui.pro ) && make -f Makefile 
Project MESSAGE: Version of this build: 1.1.1
Project ERROR: Unknown module(s) in QT: quickcontrols2
make: *** [Makefile:46: sub-ykman-gui-make_first] Error 3
```

Having `dnf install`-ed the `qt5-qtquickcontrols2` package, I don't understand what's still missing?

**Comment by vorburger** [comment]
> I don't understand what's still missing?

[just needed](https://github.com/Yubico/yubikey-manager-qt/commit/50f65fa930017e684e208e3ae287206d76097f52) the respective `-devel` packages, now builds fine.

Now another problem when starting it, anyone got a clue what this means / which package it needs:

```
$ ./ykman-gui
QQmlApplicationEngine failed to load component
qrc:/qml/main.qml:30 Type Header unavailable
qrc:/qml/Header.qml:4 module "QtQuick.Dialogs" is not installed

[1]    18104 segmentation fault (core dumped)  ./ykman-gui
```

**Comment by dagheyman** [comment]
Could it be the `qt5-qtquickcontrols` package that is missing? In the debian world my guess would be the `qml-module-qtquick-dialogs` package, but not sure it's split up in the same way in Fedora.

**Comment by vorburger** [comment]
> Could it be the qt5-qtquickcontrols package that is missing? 

yup! That helps; so `qt5-qtquickcontrols2-devel` for build and `qt5-qtquickcontrols` at runtime.

FTR, the next problem was:

```
./ykman-gui                         
QQmlApplicationEngine failed to load component
qrc:/qml/main.qml:106 Type YubiKey unavailable
qrc:/qml/YubiKey.qml:2 module "io.thp.pyotherside" is not installed

[1]    3977 segmentation fault (core dumped)  ./ykman-gui
```

and installing the package named simply `pyotherside` on Fedora took care of that - it now starts!!

I'll raise a PR for the doc with these findings in a sec.
