### ISSUE TITLE
YubiKey Manager is stuck on the "Insert your YubiKey" screen upon launch.

### ISSUE THREAD

**Issue by cwiemann** [Yubico/yubikey-manager-qt#194]
Key is recognized as a USB device in System Report, but YubiKey Manager is stuck on the "Insert your YubiKey" screen upon launch.

(Yubico Authenticator is also stuck on "No YubiKey Detected" screen upon launch.)

**Comment by cwiemann** [comment]
Mac OS 10.12.6 and Yubikey 4 OTP+U2F+CCID.

**Comment by ybaumy** [comment]
with fedora 30 I have the same issue using the appimage version

**Comment by pcrockett** [comment]
#197 might be a duplicate of this issue

**Comment by teambates** [comment]
Hi I have the same issue

I configured my Yubikey NFC with Gnupg on the terminal and I can access the device with authenticator. So not sure what the problem is.

I have installed lates Mac Version on High Sierra.
Any help welcome
