### ISSUE TITLE
Linux: YubiKey not detected in YubiKey Manager

### ISSUE THREAD

**Issue by zskamljic** [Yubico/yubikey-manager-qt#197]
When key is plugged in I can confirm login in Chrome, I can enter password via long-press, however YubiKey Manager does not detect the key when plugged in. 

I'm using YubiKey 5 NFC with kernel 5.2.11-arch1-1-ARCH. Here's dmesg output when plugging it in: 
```
[  256.004772] usb 2-3: New USB device found, idVendor=1050, idProduct=0407, bcdDevice= 5.12
[  256.004777] usb 2-3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[  256.004780] usb 2-3: Product: YubiKey OTP+FIDO+CCID
[  256.004783] usb 2-3: Manufacturer: Yubico
[  256.008129] input: Yubico YubiKey OTP+FIDO+CCID as /devices/pci0000:00/0000:00:14.0/usb2/2-3/2-3:1.0/0003:1050:0407.000A/input/input28
[  256.063433] hid-generic 0003:1050:0407.000A: input,hidraw0: USB HID v1.10 Keyboard [Yubico YubiKey OTP+FIDO+CCID] on usb-0000:00:14.0-3/input0
[  256.064153] hid-generic 0003:1050:0407.000B: hiddev0,hidraw1: USB HID v1.10 Device [Yubico YubiKey OTP+FIDO+CCID] on usb-0000:00:14.0-3/input1
```

I've added the following to /etc/udev/rules.d/10-security-key.rules:
 `KERNEL="hidraw*", SUBSYSTEM=="hidraw", MODE="0664", GROUP="users", ATTRS{idVendor}=="2581", ATTRS{idProduct}="f1d0"`
and relogged and rebooted, the problem persists.

Perhaps worth noting is that when plugging it in the light flashes for a short time (<0.5s) and turns off.

**Comment by pcrockett** [comment]
I'm having this exact same issue on Manjaro 18.1.1, except I'm using the [70-u2f.rules file][1]. The key does work (I just logged into GitHub with it).

[1]: https://github.com/Yubico/libu2f-host/blob/master/70-u2f.rules

**Comment by pcrockett** [comment]
Found the solution [on Reddit][1]. You have to make sure the `pcscd` service is running:

```
sudo systemctl start pcscd
```

Should this be added to the readme under the [Installation][2] section? I haven't found anything like this documented by Yubico and it seems fairly important. Same goes with the CLI version of this tool.

[1]: https://www.reddit.com/r/ManjaroLinux/comments/dfp4ej/yubico_authenticator_not_working_in_manjaro/
[2]: https://github.com/Yubico/yubikey-manager-qt/#installation

**Comment by zskamljic** [comment]
thanks, @pcrockett, this has fixed my issue, and I agree with you that if this is required it should be documented.

**Comment by emlun** [comment]
Yeah, thanks both of you for pointing this out! This should soon be fixed by #216.

**Comment by rmdes** [comment]
Having the exact same issue on Fedora 40
but `ykman list` works just fine, using the key with sudo or gdm/login also works just fine.

**Comment by rahra** [comment]
Same problem here on Ubuntu 24.04: ykman works, ykman-gui does not.
I think it is a problem of the GUI tool. If you start it on the command line it constantly spits out the following error messages:
```
$ ykman-gui
qrc:/qml/main.qml:96:5: QML Shortcut: Shortcut: Only binding to one of multiple key bindings associated with 4. Use 'sequences: [ <key> ]' to bind to all of them.
"PyOtherSide error: invalid syntax (yubikey.py, line 80)"
qml: Cannot import module: yubikey (invalid syntax (yubikey.py, line 80))
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
qml: Function not found: 'yubikey.init' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
```
