### ISSUE TITLE
Yubikey Y-255 not recognized on OpenBSD 6.6 (with all syspatch patches applied)

### ISSUE THREAD

**Issue by SenorAgosto** [Yubico/yubikey-manager-qt#221]
*Yubikey-manager-qt* is not detecting my Yubikey Y-255 key. 

I have installed `pcsc-lite` and `pcsc-tools`, and `pcscd` is running. When I insert my Yubikey, the OS seems to recognize it. 

Here is what is in `/var/log/messages` after insertion:
> Dec 21 17:31:23 hostname /bsd: uhidev0 at uhub0 port 2 configuration 1 interface 0 "Yubico Security Key by Yubico" rev 2.00/5.24 addr 4
>Dec 21 17:31:23 hostname /bsd: uhidev0: iclass 3/0
>Dec 21 17:31:23 hostname /bsd: uhid0 at uhidev0: input=64, output=64, feature=0

![yubikey-manager-qt](https://user-images.githubusercontent.com/250468/71315115-78f10600-241b-11ea-826c-22f687e8480d.png)

**Comment by fdennis** [comment]
Hi,
Thanks for the report!
What version of Yubikey Manager are you running?

**Comment by SenorAgosto** [comment]
Sorry, should have mentioned that. I'm running yubikey-personalization-gui **3.1.25** from [ports](https://cdn.openbsd.org/pub/OpenBSD/6.6/packages/amd64/yubikey-personalization-gui-3.1.25p1.tgz).

**Comment by fdennis** [comment]
That is not YubiKey Manager, but YubiKey Personalization Tool, which is no longer under active development. Have you tried yubikey manager? There is a [CLI](https://developers.yubico.com/yubikey-manager/) and [GUI](https://developers.yubico.com/yubikey-manager-qt/)

**Comment by dagheyman** [comment]
It looks like you have a Security Key by Yubico, which only has the FIDO protocol and is thus not supported by the YubiKey Personalization Tool. You should be able to detect it with yubikey-manager as mentioned above.

**Comment by SenorAgosto** [comment]
@dagheyman @fdennis 

Just an FYI, using yubikey-manager didn't work either. Using `pip` I installed `yubikey-manager` *3.1.0*. Then I ran `ykman list --serials` and *fido2* python package raised an exception:

> Exception: Unsupported platform: openbsd6

Do I need to manually install *libfido2* for *fido2* to work?

**Comment by emlun** [comment]
OpenBSD support has been [merged into `python-fido2`](https://github.com/Yubico/python-fido2/pull/82), but is not yet released.

**Comment by SenorAgosto** [comment]
@emlun any idea when the next release is coming?

**Comment by emlun** [comment]
Sorry, we don't know at this time.
