### ISSUE TITLE
Releases page missing signed tarball for 1.1.4

### ISSUE THREAD

**Issue by Foxboron** [Yubico/yubikey-manager-qt#232]
Hi,

yubikey-manager-qt is currently missing a source release tarball on the release page. It seems like it's been replaced by an Appimage, but this can't be packaged by distributions and the github tarballs are missing signatures.

**Comment by dagheyman** [comment]
Thanks, this is an oversight on our part, the source package will be available later today.

**Comment by Foxboron** [comment]
Awesome, thank you!

**Comment by dagheyman** [comment]
Download available here https://developers.yubico.com/yubikey-manager-qt/Releases/

Thanks for letting us know!
