### ISSUE TITLE
Update release note of GitHub

### ISSUE THREAD

**Issue by kenchan0130** [Yubico/yubikey-manager-qt#246]
I subscribe to the release notes of this project to detect the latest release with feed.
The current version is 1.1.5, but the latest release note is 1.1.4.

I know https://developers.yubico.com/yubikey-manager-qt/Releases/  has a list, but I can't subscribe to see if it's up to date, either.

I hope to have that release note made when the latest version is released.

**Comment by fdennis** [comment]
That's my bad! Thank you for letting us know.
I have now updated the release notes on GitHub.

**Comment by kenchan0130** [comment]
Thanks a lot for your work.
