### ISSUE TITLE
Linux software release signing key

### ISSUE THREAD

**Issue by JazzTp** [Yubico/yubikey-manager-qt#248]
Hi,

https://developers.yubico.com/yubikey-manager-qt/Releases/

**yubikey-manager-qt-1.1.5-linux.AppImage** has apparently been signed with
key **D6919FBF48C484F3CB7B71CD870B88256690D8BC**

I don't find it in this page:
https://developers.yubico.com/Software_Projects/Software_Signing.html

Where should I get the signing key please?

**Comment by nevun** [comment]
It is signed by dennis.fokin@yubico.com, D6919FBF48C484F3CB7B71CD870B88256690D8BC is his subkey used for signing. Import the key for Dennis from our Software Signing page and then you will be able to verify the signature:

```
$ gpg --verify yubikey-manager-qt-1.1.5-linux.AppImage.sig 
gpg: assuming signed data in 'yubikey-manager-qt-1.1.5-linux.AppImage'
gpg: Signature made tor 13 aug 2020 11:52:23 CEST
gpg:                using RSA key D6919FBF48C484F3CB7B71CD870B88256690D8BC
gpg: Good signature from "Dennis Fokin <dennis.fokin@yubico.com>" [expired]
gpg: Note: This key has expired!
Primary key fingerprint: 9E88 5C03 02F9 BB91 6752  9C2D 5CBA 11E6 ADC7 BCD1
     Subkey fingerprint: D691 9FBF 48C4 84F3 CB7B  71CD 870B 8825 6690 D8BC
```

**Comment by JazzTp** [comment]
> It is signed by [dennis.fokin@yubico.com](mailto:dennis.fokin@yubico.com), D6919FBF48C484F3CB7B71CD870B88256690D8BC is his subkey used for signing. Import the key for Dennis from our Software Signing page and then you will be able to verify the signature:
> 
> ```
> $ gpg --verify yubikey-manager-qt-1.1.5-linux.AppImage.sig 
> gpg: assuming signed data in 'yubikey-manager-qt-1.1.5-linux.AppImage'
> gpg: Signature made tor 13 aug 2020 11:52:23 CEST
> gpg:                using RSA key D6919FBF48C484F3CB7B71CD870B88256690D8BC
> gpg: Good signature from "Dennis Fokin <dennis.fokin@yubico.com>" [expired]
> gpg: Note: This key has expired!
> Primary key fingerprint: 9E88 5C03 02F9 BB91 6752  9C2D 5CBA 11E6 ADC7 BCD1
>      Subkey fingerprint: D691 9FBF 48C4 84F3 CB7B  71CD 870B 8825 6690 D8BC
> ```

Thank you.
As I had no keys previously imported from Yubico, I was only getting this answer from gpg:

```
$ gpg --verify yubikey-manager-qt-1.1.5-linux.AppImage.sig yubikey-manager-qt-1.1.5-linux.AppImage
gpg: Signature made Thu 13 Aug 2020 09:52:23 AM UTC
gpg:                using RSA key D6919FBF48C484F3CB7B71CD870B88256690D8BC
gpg: Can't check signature: No public key
$
```

I couldn't link that information to any key in the [Software Signing page](https://developers.yubico.com/Software_Projects/Software_Signing.html).

You may consider adding a note under the title on that page, something like:

**"You can search in https://keys.openpgp.org/ any key or subkey ID found in a signature on our software and not appearing in this page, then please check that it actually belongs to one of the developers in the list below."**
