### ISSUE TITLE
Access Restriction Codes

### ISSUE THREAD

**Issue by MassiveStorage** [Yubico/yubikey-manager-qt#249]
Hi i noticed that with the new YubiKey-Manager-QT that should be used instead of YubiKey Personalization Tool, you are no longer able to set/remove slot access restriction codes. I think this was a very important feature of the slot configuration and should be added to YubiKey-Manager-QT as well. And being able to save the configuration that have been written to the yubikey as an exportfile (maybe even encrypted) should also be possible.

**Comment by nevun** [comment]
I cannot comment on the GUI part but it is available on the CLI version of Yubikey-Manager:

```
$ ykman otp settings --help
Usage: ykman otp settings [OPTIONS] [1|2]

  Update the settings for a slot.

  Change the settings for a slot without changing the stored secret. All settings not specified will be written with default values.

Options:
  -f, --force                Confirm the action without prompting.
  -A, --new-access-code HEX  Set a new 6 byte access code for the slot. Set to empty to use a prompt for input.
  --delete-access-code       Remove access code from the slot.
  --enter / --no-enter       Should send 'Enter' keystroke after slot output.  [default: True]
  -p, --pacing [0|20|40|60]  Throttle output speed by adding a delay (in ms) between characters emitted.  [default: 0]
  --use-numeric-keypad       Use scancodes for numeric keypad when sending digits. Helps with some keyboard layouts.   [default:
                             False]
  -h, --help                 Show this message and exit.
$ 
```

**Comment by fdennis** [comment]
Hi, and thanks for your suggestion. As @nevun said, this is available in the CLI. The GUI does not support this and there are currently no plans to add this feature.

**Comment by MassiveStorage** [comment]
Ok. If this feature is still accessible (even not as comfortable as in the previous tool) i can live with that.
