### ISSUE TITLE
Cannot configure newline after autotype

### ISSUE THREAD

**Issue by MechMK1** [Yubico/yubikey-manager-qt#251]
The YubiKey Personalization Tool allowed users to configure the exact sequence sent by the YubiKey when touched, including the ability to configure if an <kbd>Enter</kbd> keypress should be simulated after the sequence is completed.

The new YubiKey Manager does not allow such configuration yet. This missing function should be added.

**Comment by fdennis** [comment]
Hey,
Could you explain what exactly you would like to accomplish? Through [ykman cli](https://github.com/Yubico/yubikey-manager) you can configure if `Enter` should be sent or not after slot output. Would that be what you are looking for?

**Comment by jstrese** [comment]
@fdennis I think that's what @MechMK1 is asking. I came here to ask the same thing. 

It would be extremely appreciated if the ability to enable/disable the `Enter` keystroke. It causes issues in forms that have other inputs and opens you up to accidentally sending input to non-secure channels like a chat program.

**Comment by MechMK1** [comment]
@fdennis Sorry for the delayed response, I completely forgot I had raised this issue.

My use-case is as follows: I use the static password feature on my YubiKey Nano, and have configured it to require a long-press before entering. Due to the design of the Yubikey Nano and the way I hold my laptop, it can at times happen that I accidentally touch the sides of the Yubikey, which causes it to input the static password. If I happen to be typing in a chat room or other such window, where pressing <kbd>Enter</kbd> would cause a message being sent, then that would cause disclosure of my password - something I would ideally avoid.

One way of avoiding this would be to prevent the <kbd>Enter</kbd> keystroke from being sent after the password. This option is already available in the Yubikey Personalization Tool, shown in the following screenshot:

![Yubikey Personalization Tool - Output Format](https://user-images.githubusercontent.com/979843/105920298-6a6e1880-6037-11eb-8f6e-b5baffddc050.PNG)

This setting, when configured in Static Password mode, allows me to remove the trailing <kbd>Enter</kbd> keystroke when the static password is being typed. I would like to see this same feature in the more modern Yubikey Manager.

As for the command-line tool you mentioned, it seems that the `--no-enter` flag provides this configuration option, but the QT manager seems to be lacking it.

**Comment by fdennis** [comment]
Thank you for letting us know about your use-cases.
As previously mentioned, you can configure whether to send an ENTER keystroke after the output has been written in ykman cli.
Example: `ykman otp static --no-enter [PASSWORD]`
This does not yet exist in the GUI, because we want to keep it as clean and simple as possible. We will take your opinions into consideration and might add it if we see a larger demand for it.

**Comment by fdennis** [comment]
I will close this issue for now and refer to my comment just above from Jan 27. If there is more demand for this we might consider adding it, but right now this can be solved with ykman cli.

**Comment by jstrese** [comment]
When your mission to keep a UI clean and simple ends up restricting usability, you've failed.

This is a basic feature that can only be accessed using the CLI. You should really think about adding it back in, or at least re evaluate your "clean" interface logic. Add a simple checkbox. Or a button to open advanced settings. It's not that difficult guys.
