### ISSUE TITLE
Sign of AppImage from unknown developer

### ISSUE THREAD

**Issue by noppelmax** [Yubico/yubikey-manager-qt#254]
Hey,

i downloaded the `yubikey-manager-qt-1.1.5-linux.AppImage.sig` file a moment ago. I checked the signature and it seems to be from someone not listed here: https://developers.yubico.com/Software_Projects/Software_Signing.html

Linux Terminal:
```
max@merry:~/Downloads$ gpg --with-fingerprint yubikey-manager-qt-1.1.5-linux.AppImage.sig 
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
gpg: assuming signed data in 'yubikey-manager-qt-1.1.5-linux.AppImage'
gpg: Signature made Do 13 Aug 2020 11:52:23 CEST
gpg:                using RSA key D6919FBF48C484F3CB7B71CD870B88256690D8BC
gpg: Can't check signature: No public key
```

Am I doing something wrong or is this key just not listed?

Kind regards,
Max

**Comment by fdennis** [comment]
Hi,
And sorry for the late reply!
You seem to be having the same issue as #248 
It is signed by me and D6919FBF48C484F3CB7B71CD870B88256690D8BC is my subkey. You need to import my key to verify the signature. Please, read through #248 for more detailed instructions.

**Comment by jonathancross** [comment]
@fdennis Please consider having your pgp key cross signed with somebody in the Open PGP Web Of Trust "Strong Set"
This will allow users to verify the authenticity of the key and ID info without [blindly trusting](https://developers.yubico.com/Software_Projects/Software_Signing.html) a website such as github or yubico.com

This should be standard practice for anyone who signing software, especially security-related software like you do.

Thanks 🙏
