### ISSUE TITLE
YubiKey Manager wont install on M1 Mac (MacOS BigSur 11.2.1)

### ISSUE THREAD

**Issue by Andixon** [Yubico/yubikey-manager-qt#259]
Hi,

unfortunately the YubiKey Manager wont install on my Apple Silicon Mac under MacOS Big Sur 11.2.1
The installation finishes without issues, but I cant find the app anywhere on my Mac.

For details see the attached installer log.

[installer_log 19-Feb-2021.txt](https://github.com/Yubico/yubikey-manager-qt/files/6009351/installer_log.19-Feb-2021.txt)

**Comment by fdennis** [comment]
Hi,
Sorry for the late reply.
We have successfully installed YubiKey Manager GUI on our M1 Macs. Make sure you do not have an old version of YubiKey Manager installed anywhere. Are you still seeing this problem?

**Comment by Andixon** [comment]
Hi, 

sorry I didn't react sooner. Unfortunately I still see the problem. I use the newest version of Mac OS Big Sur and also the newest version of the YubiKey Manager. Also there was never a version of the YubiKey Manager installed on this machine. This was the first time that I needed it.

**Comment by fdennis** [comment]
It installs successfully but you cannot find it anywhere, not even in /Applications, is that correct?

**Comment by Andixon** [comment]
Weirdly it did work now, when I tried it again. But then I tried to reproduce it, so I deleted the program from /Applications and used the same package to install it again and now it didn't work. I repeated the process several times, but it won't show up in /Applications or anywhere again. It worked just this once.

**Comment by fdennis** [comment]
@Andixon I will close this since we have successfully installed it on multiple M1 Macs, and you managed to get it working at some point at least once. It is difficult for me to say more than that. We have not seen this problem with other users either. If you have more information, please provide it.
