### ISSUE TITLE
Upload YubiOTP credential to YubiCloud not possible

### ISSUE THREAD

**Issue by M289** [Yubico/yubikey-manager-qt#262]
Using macOS YubiKey Manager QT version 1.1.5b, upload of YubiOTP credential to YubiCloud not possible.

Error: "Upload failed: Failed to open HTTPS connection. Credential not configured."

![YubiKey Manager QT Upload Yubico OTP failed 20210303](https://user-images.githubusercontent.com/24386886/109812451-5ddb7200-7c2c-11eb-898e-9ebdbb871acb.png)

**Comment by fdennis** [comment]
Thanks for letting us know.
You are correct, this is an issue on Mac. We will look into this.

**Comment by M289** [comment]
Thanks @fdennis :-)
For what it's worth, running macOS version 11.2.2 (20D80) on the Intel platform.

I don't believe there is a Apple M1 platform package yet right? Neither for YubiKey Manager, Yubico Authenticator or Personalisation Tool.

**Comment by fdennis** [comment]
@M289 They should all work on the M1.

**Comment by M289** [comment]
> @M289 They should all work on the M1.

Alright, but there are no native M1 packages yet correct?

**Comment by dainnilsson** [comment]
> Alright, but there are no native M1 packages yet correct?

That is correct. The ykman CLI is available for M1 through Homebrew though.

**Comment by M289** [comment]
> > Alright, but there are no native M1 packages yet correct?
> 
> That is correct. The ykman CLI is available for M1 through Homebrew though.

Thanks for the tip!

**Comment by fdennis** [comment]
Please try updating to the latest version, 1.2.0, and see if that helps. Reopen this issue if it does not.

**Comment by jbb26354** [comment]
OSX version: Monterey, 12.1
Yubikey manager for mac, version: 1.2.4, downloaded 12-24-2021

Still fails.

**Comment by bryq** [comment]
Hi! The same on Windows 10, YKM 1.2.4

![ye](https://user-images.githubusercontent.com/6084417/147506248-90f3ef4f-90f9-418b-9981-6e1ed2ae73a0.JPG)

**Comment by fdennis** [comment]
@jbb26354 @bryq Could you run the application through a terminal with the debug flag? Like this
`ykman-gui --log-level DEBUG`
and post the stack trace / error here? Basically, I want to verify that you are having the exact same issue.

Also, as a workaround, you could manually visit https://upload.yubico.com/ and fill in everything from the GUI. In that case, do not check the "upload" checkbox.

**Comment by bryq** [comment]
Hi! It has started to work - no error while check Upload and Finish. 
Thank you and regards!
