### ISSUE TITLE
Yubikey Manager stuck at "Insert your Yubikey" reporting "NameError: name 'yubikey' is not defined" → "Function not found: 'yubikey.controller.count_devices'"

### ISSUE THREAD

**Issue by bentolor** [Yubico/yubikey-manager-qt#263]
I'm on Ubuntu 20.04 with `deb http://ppa.launchpad.net/yubico/stable/ubuntu focal main` enabled.

```
$ apt show yubikey-manager-qt
Package: yubikey-manager-qt
Version: 1.1.3~ppa1~eoan1
Status: install ok installed
```

The Yubikey Manager stopped working at some time. Possibly due to some `ykman` update? `ykman` itself is working without issues.

It is stuck at the "Insert you yubikey" screen. Starting it from CLI keep repeating the following output into the console:

```
 $ ykman-gui
Got library name:  "/usr/lib/x86_64-linux-gnu/qt5/qml/io/thp/pyotherside/libpyothersideplugin.so"
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:///py/yubikey.py\", line 19, in <module>\n    from fido2.ctap import CtapError\n\nModuleNotFoundError: No module named 'fido2'\n"
qml: Cannot import module: yubikey (Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 19, in <module>
    from fido2.ctap import CtapError

ModuleNotFoundError: No module named 'fido2'
)
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
qml: Function not found: 'yubikey.init' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: qrc:/qml/YubiKey.qml:263: Error: Cannot assign [undefined] to int
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
```

**Comment by bentolor** [comment]
Uhhh… just realized that it's no longer up-to-date and using the AppImage works. Related to #238. My bad.

As I  already mentioned in I find the lack of system integration with AppImage frustrating. Next time the App stops working I'll probably find myself opening another issue here until I realized how & when & why I need some specific Voodoo only for this app to keep it running.

I understand the packaging pain, but Snap and Flatpak distributions at least offer System Integration (i..e launch  menu) and an (automated) update-facility.

**Comment by fdennis** [comment]
@bentolor As you have pointed out, the AppImage is the supported distribution format for Linux. I understand that this might not be ideal. If there is a community effort to package for something else we will try to help out as much as we can. I also want to point out that if you are comfortable using the terminal, we have a [CLI ](https://github.com/Yubico/yubikey-manager).
