### ISSUE TITLE
Feature request: Configure NDEF slot for NFC usage

### ISSUE THREAD

**Issue by M289** [Yubico/yubikey-manager-qt#270]
Feature request: Configure the NDEF slot for NFC usage with compatible YubiKey.

Currently only possible with the (old) YubiKey Personalization Tool,

**Comment by fdennis** [comment]
Hi,
This is available in [ykman cli ](https://github.com/Yubico/yubikey-manager).
`ykman otp ndef [OPTIONS] [1|2]`
 There are no plans of adding this to the GUI yet, since we want to careful think through every decision made. If there is a larger demand for this we might consider it.

**Comment by M289** [comment]
Alright, thank you. Configuring it using the ykman cli works.

Having a full features GUI management tool would be nice though.

**Comment by fdennis** [comment]
I will close this for now. If there is a larger demand we might reconsider this.
