### ISSUE TITLE
YubiKey Manager stuck on "Insert your YubiKey" (MacOS 11.2.3 Big Sur)

### ISSUE THREAD

**Issue by aastein** [Yubico/yubikey-manager-qt#279]
When I launch YubiKey Manager I can't get past this screen:
![image](https://user-images.githubusercontent.com/18291415/115162513-a5348b00-a03f-11eb-9294-9253b2aa27a5.png)

I am able to open YubiKey Personalization Tool, and my YubiKey is detected.
![image](https://user-images.githubusercontent.com/18291415/115162554-eaf15380-a03f-11eb-8b83-95cd71a27fe1.png)

**YubiKey**
YubiKey 5C Nano
SKU: 5060408461518

**Computer:**
MacBook Pro 13-inch (2 USB ports)
Mac OS 11.2.3 (Big Sur)
M1 Chip

**Comment by fdennis** [comment]
What version are you running?

**Comment by aastein** [comment]
Version 1.2.2

**Comment by aastein** [comment]
running the command line tool (as admin and not admin) results in similar behavior. The command hangs and does not listen for signal interrupt `^C`/`^D`

```
aaron@Aarons-MBP ~ % sudo ykman -l DEBUG list --serials
Password:
2021-04-21T09:09:33-1000 INFO [ykman.logging_setup.setup:74] Initialized logging for level: DEBUG
2021-04-21T09:09:33-1000 INFO [ykman.logging_setup.setup:75] Running ykman version: 4.0.2
2021-04-21T09:09:33-1000 DEBUG [ykman.logging_setup.log_sys_info:47] Python: 3.9.4 (default, Apr  4 2021, 17:42:23) 
[Clang 12.0.0 (clang-1200.0.32.29)]
2021-04-21T09:09:33-1000 DEBUG [ykman.logging_setup.log_sys_info:48] Platform: darwin
2021-04-21T09:09:33-1000 DEBUG [ykman.logging_setup.log_sys_info:54] Running as admin: True
```

**Comment by aastein** [comment]
@fdennis do you know of any way to turn off a yubikey's OTP without using the manager? is there any way to accomplish this using the personalization tool?

**Comment by fdennis** [comment]
@aastein Could you try installing [ykman cli](https://github.com/Yubico/yubikey-manager) through homebrew and see if that works better? Instructions are available [here](https://formulae.brew.sh/formula/ykman#default).

**Comment by aastein** [comment]
Weird. It was installed with brew. So I reinstalled it, which reinstalled the same version 4.0.2, and now things are working. 🤷‍♂️

**Comment by paulrberg** [comment]
I was encountering the same issue that @aastein went through when the Yubikey was inserted face-up (Yubico logo up). I switched to face-down and it worked.
