### ISSUE TITLE
ykman piv certificates import results in Could not open file on MacOS 10.15

### ISSUE THREAD

**Issue by YT3DEO** [Yubico/yubikey-manager-qt#280]
- YubiKey Manager (ykman) version: 4.0.1
- How was it installed?: MacOS Package Installer for Yubikey Manager 1.0
- Operating system and version: MacOS 10.15 (Catalina)
- YubiKey model and version: Yubikey FIPS, version 4.4.5
- Bug description summary: piv import Could not Open File 

Steps to reproduce
1) Add /Applications/YubiKey Manager.app/Contents/MacOS/ykman to path
2) Generate private key and certificate signing request on Yubikey.
3) Sign CSR to generate Cert.
4) (a) Run ykman piv certificates import -m <management key> 9c certificate.crt

      Error: Invalid value for 'CERTIFICATE': Could not open file: certificate.crt: No such file or directory

4) (b) Same certificate, using Yubikey Manager, PIV application, Import button on slot 9c.  

      Error 1: Operation Not Permitted. </Path/To/certificate.crt>
---

I did not repeat the testing in other slots.

Expected result
---

Testing the import function using a Windows 10 install of Yubikey Manager with the same key + certificate and Yubikey results in a successful import into the slot.  

Actual results and logs
---

CLI: Error: Invalid value for 'CERTIFICATE': Could not open file: certificate.crt: No such file or directory

GUI: Error 1: Operation Not Permitted. </Path/To/certificate.crt>

Other info
---

The same machine, yubikey and CA infrastructure can successfully generate a key and certificate that will import properly with version ykman 3.1.2 installed with MacPorts.

Test results in same after giving Yubikey Manager app full disk access and allowing to manage machine (Accessibility) in Preferences >> Security & Privacy >> Privacy.

**Comment by fdennis** [comment]
Hi,
Could you check the permissions of `certificate.crt` and make sure they are correct?

**Comment by YT3DEO** [comment]
The certificate file mode is 644.  Owner rw, group read, world read.  I'm not sure what "correct" is supposed to be.  In this case the owner of the cert file is the user executing the import operation, so the permissions should logically be sufficient.

Note: no changes were made to file permissions.  This is as generated by openssl ca operations.

**Comment by fdennis** [comment]
Regarding the `No such file or directory` error with the cli.
Could you, with ykman cli, try the same command but write the absolute path and see if that changes anything?
Instead of 
`ykman (..) 9c certificate.crt`
write
`ykman (..) 9c /path/to/certificate.crt`

**Comment by fdennis** [comment]
Thank you for letting us know about this. We have confirmed and found a few issues. We will shortly be releasing a version 1.2.3 addressing all of these. In the meantime, a workaround that you can try is to use ykman cli from homebrew.

**Comment by YT3DEO** [comment]
@fdennis  Updated to Yubikey Manager 1.2.3 (ykman 4.0.3)...and imports of certificates are now working as expected.
