### ISSUE TITLE
PIV certificate import issue

### ISSUE THREAD

**Issue by glop2801** [Yubico/yubikey-manager-qt#287]
Hi Team,

Context: win 10 1909
Yubikey 5 NFC , firmware version 5.2.4
Yubikey minidriver 4.1.1.210

I can install a PIV certificate on my windows machine (p12/pfx format)
I can install the certificate on any slot of the Yubikey using yubico-piv-tool 2.1.1

But, using Yubikey Manager qt version 1.2.1 or 1.2.2  (i do not have this issue with 1.1.5)

using ykman or ykman-gui , log-level DEBUG:

Enter password to decrypt certificate:
2021-05-12T08:33:05+0200 DEBUG [ykman.util.parse_certificates:156] Failed to parse certificate as DER
Traceback (most recent call last):
  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\util.py", line 154, in parse_certificates
    return [x509.load_der_x509_certificate(data, default_backend())]
  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\cryptography\x509\base.py", line 404, in load_der_x509_certificate
    return backend.load_der_x509_certificate(data)
  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\cryptography\hazmat\backends\openssl\backend.py", line 1358, in load_der_x509_certificate
    raise ValueError("Unable to load certificate")
ValueError: Unable to load certificate
Wrong password.

thanks for all your work

Glop

**Comment by dainnilsson** [comment]
Can you provide more details on the exact steps your running? And if possible, an example certificate file that can be used to reproduce this?

**Comment by glop2801** [comment]
Thanks for your answer, difficult to me to send you a cert example, sorry.

Simply running the command:
yubico-piv-tool -a import-key -a import-certificate -s 82 -k -i <p12 cert file>   : works fine.

ykman.exe --log-level DEBUG piv certificates import 82 <p12 cert file>  Fail.
(slot 82, or 9a , 9c ...), same result for both commands.
When i use the GUI, i have a red message on the bottom, "Failed to parse file".

Hope this help.

**Comment by dainnilsson** [comment]
Am I understanding you correctly that you're running `ykman.exe piv certificates import 82 filename.pfx`, where filename.pfx contains both a key and certificate? Without a failing file it will be hard to troubleshoot, but it looks like ykman isn't able to correctly identify the file type. We have made some changes and fixes recently around this code, which might resolve this, or at least offer us some more information in the error handling. Would you be able to download the `ykman-builds-windows.zip` file from here: https://github.com/Yubico/yubikey-manager/actions/runs/816733234 and extract the `ykman-main.exe` file from it, and try running that with the same import command (just substitute `ykman.exe` for `ykman-main.exe`)? Note that this file is not signed by Yubico, so you may get some warnings from Windows when running it.

**Comment by glop2801** [comment]
Yes, the pfx contains key and cert. I understand that it will be hard for you to troubleshoot without the example cert, but i cannot share, if you cannot do without the cert, i fully understand.
i have this problem for some certificates only, issued by the same certificate system. It's not a question of password format, as i can have the issue with a complex or a really simple password.
I can put the "problematic" certificate on the key using Yubikey Manager V1.1.5 but not with the never versions.

below, logs running ykman-main.exe

2021-05-12T10:57:32+0200 INFO [ykman.logging_setup.setup:76] Initialized logging for level: DEBUG
2021-05-12T10:57:32+0200 INFO [ykman.logging_setup.setup:77] Running ykman version: 4.0.3-dev0
2021-05-12T10:57:32+0200 DEBUG [ykman.logging_setup.log_sys_info:48] Python: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
2021-05-12T10:57:32+0200 DEBUG [ykman.logging_setup.log_sys_info:49] Platform: win32
2021-05-12T10:57:32+0200 DEBUG [ykman.logging_setup.log_sys_info:50] Arch: AMD64
2021-05-12T10:57:32+0200 DEBUG [ykman.logging_setup.log_sys_info:52] Windows version: (10, 0, 18363)
2021-05-12T10:57:32+0200 DEBUG [ykman.logging_setup.log_sys_info:56] Running as admin: False
2021-05-12T10:57:32+0200 DEBUG [ykman.pcsc.send_and_receive:118] SEND: 00a4040008a000000527471117
2021-05-12T10:57:32+0200 DEBUG [ykman.pcsc.send_and_receive:120] RECV: 5669727475616c206d6772202d2046572076657273696f6e20352e322e34 SW=9000
2021-05-12T10:57:32+0200 DEBUG [ykman.pcsc.send_and_receive:118] SEND: 001d000000
2021-05-12T10:57:32+0200 DEBUG [ykman.pcsc.send_and_receive:120] RECV: 2e0102023f0302023f020400b7531604010105030502040602000007010f0801000d02023f0e02023f0a01000f0100 SW=9000
2021-05-12T10:57:32+0200 DEBUG [ykman.device.read_info:453] Read info: DeviceInfo(config=DeviceConfig(enabled_capabilities={<TRANSPORT.USB: 'usb'>: <CAPABILITY.FIDO2|OATH|PIV|OPENPGP|4|U2F|OTP: 575>, <TRANSPORT.NFC: 'nfc'>: <CAPABILITY.FIDO2|OATH|PIV|OPENPGP|4|U2F|OTP: 575>}, auto_eject_timeout=0, challenge_response_timeout=15, device_flags=<DEVICE_FLAG.0: 0>), serial=12014358, version=Version(major=5, minor=2, patch=4), form_factor=<FORM_FACTOR.USB_A_KEYCHAIN: 1>, supported_capabilities={<TRANSPORT.USB: 'usb'>: <CAPABILITY.FIDO2|OATH|PIV|OPENPGP|4|U2F|OTP: 575>, <TRANSPORT.NFC: 'nfc'>: <CAPABILITY.FIDO2|OATH|PIV|OPENPGP|4|U2F|OTP: 575>}, is_locked=False, is_fips=False)
2021-05-12T10:57:32+0200 DEBUG [ykman.pcsc.send_and_receive:118] SEND: 00a4040005a000000308
2021-05-12T10:57:32+0200 DEBUG [ykman.pcsc.send_and_receive:120] RECV: 61114f0600001000010079074f05a000000308 SW=9000
2021-05-12T10:57:32+0200 DEBUG [ykman.pcsc.send_and_receive:118] SEND: 00fd000000
2021-05-12T10:57:32+0200 DEBUG [ykman.pcsc.send_and_receive:120] RECV: 050204 SW=9000
2021-05-12T10:57:32+0200 DEBUG [ykman.pcsc.send_and_receive:118] SEND: 00cb3fff0000055c035fff00
2021-05-12T10:57:32+0200 DEBUG [ykman.pcsc.send_and_receive:120] RECV: 53058003810102 SW=9000
2021-05-12T10:57:32+0200 DEBUG [ykman.util.parse_certificates:165] Failed to parse certificate as DER
Traceback (most recent call last):
  File "ykman\util.py", line 163, in parse_certificates
  File "cryptography\x509\base.py", line 404, in load_der_x509_certificate
  File "cryptography\hazmat\backends\openssl\backend.py", line 1358, in load_der_x509_certificate
ValueError: Unable to load certificate
2021-05-12T10:57:33+0200 ERROR [ykman.cli.__main__.main:379] Error
Traceback (most recent call last):
  File "ykman\cli\__main__.py", line 371, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "ykman\cli\piv.py", line 755, in import_certificate
  File "ykman\util.py", line 167, in parse_certificates
ValueError: Could not parse certificate.
Error: Could not parse certificate.

**Comment by glop2801** [comment]
anther comment, and no idea if htis can help.
using a linux machine and openssl , i have no problem to manipulate my certificates.
The only difference i can see , is about "iteration", but i have no clue on the impact.

Working cert with ykman:
openssl pkcs12 -info -in <certFile> -noout
Enter Import Password:
MAC Iteration 1024
MAC verified OK
PKCS7 Data
Shrouded Keybag: pbeWithSHA1And3-KeyTripleDES-CBC, Iteration 1024
PKCS7 Encrypted data: pbeWithSHA1And40BitRC2-CBC, Iteration 1024
Certificate bag
Certificate bag
Certificate bag
Certificate bag

non working cert:
MAC Iteration 102400
MAC verified OK
PKCS7 Data
Shrouded Keybag: pbeWithSHA1And3-KeyTripleDES-CBC, Iteration 51200
PKCS7 Encrypted data: pbeWithSHA1And40BitRC2-CBC, Iteration 51200
Certificate bag
Certificate bag
Certificate bag
Certificate bag

**Comment by dainnilsson** [comment]
It seems that the code checking the file type is incorrectly identifying your file as not being PKCS12/PFX. We use the file structure to determine this.

Can you try running the following command on one of the non-working certs and provide part of the output?
This won't prompt for a password, so the private keys within won't be decrypted. You also don't need to include any of the HEX data within.

The file type identification code looks for the initial SEQUENCE, followed by an INTEGER of value 3. If your file doesn't have that I'd be interested in what it has instead.

```
$ openssl asn1parse -inform der -in yourcertificate.pfx

    0:d=0  hl=4 l= 944 cons: SEQUENCE
    4:d=1  hl=2 l=   1 prim: INTEGER           :03
    7:d=1  hl=4 l= 886 cons: SEQUENCE
   11:d=2  hl=2 l=   9 prim: OBJECT            :pkcs7-data
   22:d=2  hl=4 l= 871 cons: cont [ 0 ]
   26:d=3  hl=4 l= 867 prim: OCTET STRING      [HEX DUMP]:3082035F3082022406092A864886F70D010706A0820215308202110201003082020A06092A864886F70D010701304906092A864886F70D01050D303C301B06092A864886F70D01050C300E040828BCACE7FA8C28BD02020800301D060960864801650304012A041027BD21A3BB35CDD411A286A968DCD9B2808201B0AA7AB2B9B19A066368A37B717B597927B1CEDE9AEDA950E704D5C1EC2829641EABF3D759DDF86AF2B7AAA934054C38A4E7C29DE5614164BAD87A1FD156A3A4A65D196AD26B7868629CFD622798DDF7684C5918DB180B7A3937B54303D3A613A100C77BEE48A52D760624943DDD89D7085B0DB6FD8931237FADAAF6C99983F91C45EABCA80C1011557BFEB8FA102EAD7E6FCAE2EBAA92F0ABC7A7A98015A4216316DE9730D3E78308BA123945CC55749C5C76003455810C2DCE52D9170CC8647BA79EC4A452395E8D3072DE311B01AECEA56DF8B3E967E0FDA84BF6B4E67C6237CB7502679258DDA7C83776B82A349F837C4E958C881243926E45E1BD0160F39832BBF8744AE0A81FD014E7EACE21AC478B00288CECAEA6C6E6FEDCD0ACF82CD59B77326B28980CED7A72D528ACFF652EB22970A6D115DC862D13905E2BDE012BD363453543EA2255DE2DE6662AC41F8E116DFE060E3845F446AAB8C0B515F2E21340E84235A74BCDADC2677795C9BA7310A5E8898F3ADAA2246275AD3E2C4F64C90C04BF5E5F2D58782AC6170E614E409AE5B5705E56C4FDF55E05241FB477959EE2753FCEEFC6A90608ECA076412A593082013306092A864886F70D010701A0820124048201203082011C30820118060B2A864886F70D010C0A0102A081E13081DE304906092A864886F70D01050D303C301B06092A864886F70D01050C300E040876539ACB671E15BD02020800301D060960864801650304012A0410DB6E660CA7C98222D8B3E3198CE574A004819038F9405F3A5EF1C82C0C2E04830B26D079EBADC1F40B7C26329BA2554CB8EEED47B7E87A94867368E654823D68221F7F859D7CA6264403B8FAA980F4CF99D72449145D04A1EEF850C950698F13C441B987D97CE1EFAA71496A9EB2EC0647BA6F505AB1A748FB00235972553F5B246F9DC826D64C12527151D5248A48FCA02E1A6C21C8D1EB7E54B590BFF3EED28453103125302306092A864886F70D010915311604142534F63C8F948CE54827F670D924D5FC81FAA12C
  897:d=1  hl=2 l=  49 cons: SEQUENCE
  899:d=2  hl=2 l=  33 cons: SEQUENCE
  901:d=3  hl=2 l=   9 cons: SEQUENCE
  903:d=4  hl=2 l=   5 prim: OBJECT            :sha1
  910:d=4  hl=2 l=   0 prim: NULL
  912:d=3  hl=2 l=  20 prim: OCTET STRING      [HEX DUMP]:5E04A613CD10EE494641B1C37A46A15336142EEB
  934:d=2  hl=2 l=   8 prim: OCTET STRING      [HEX DUMP]:5D7F7D0BEAF29DDF
  944:d=2  hl=2 l=   2 prim: INTEGER           :0800
```

**Comment by glop2801** [comment]
Ok, thanks , for digging in this issue, much appreciated.

So , yes it's different. Below 2 samples, first one , 'problematic' , second one OK (issued by the same CA, with the same template:(This CA is not private or corporate, , but public trusted company)

 0:d=0  hl=2 l=inf  cons: SEQUENCE
    2:d=1  hl=2 l=   1 prim: INTEGER           :03
    5:d=1  hl=2 l=inf  cons: SEQUENCE
    7:d=2  hl=2 l=   9 prim: OBJECT            :pkcs7-data
   18:d=2  hl=2 l=inf  cons: cont [ 0 ]
   20:d=3  hl=2 l=inf  cons: OCTET STRING
   22:d=4  hl=4 l=1000 prim: OCTET STRING      [HEX DUMP]:3080308006092A864886F70D01070..
 1026:d=4  hl=4 l=1000 prim: OCTET STRING      [HEX DUMP]:3D47FEB4BF44384FAAF0A54BE6ED1..
 2030:d=4  hl=4 l=1000 prim: OCTET STRING      [HEX DUMP]:258E0E1A050BFC7070F87A8B809B8..
 3034:d=4  hl=4 l=1000 prim: OCTET STRING      [HEX DUMP]:23FCCFC5C7512FE1CB88CCE465863..
 4038:d=4  hl=4 l=1000 prim: OCTET STRING      [HEX DUMP]:2BFFC311FD7722C31D3A516A54E7E..
 5042:d=4  hl=4 l=1000 prim: OCTET STRING      [HEX DUMP]:D34158694AE1EC397E9744D035543..
 6046:d=4  hl=4 l=1000 prim: OCTET STRING      [HEX DUMP]:5A04308FFF05FEAA6DB23594F1AA9..
 7050:d=4  hl=4 l= 389 prim: OCTET STRING      [HEX DUMP]:5315794066869ADED2429F2CDF713..
 7443:d=4  hl=2 l=   0 prim: EOC
 7445:d=3  hl=2 l=   0 prim: EOC
 7447:d=2  hl=2 l=   0 prim: EOC
 7449:d=1  hl=2 l=  62 cons: SEQUENCE
 7451:d=2  hl=2 l=  33 cons: SEQUENCE
 7453:d=3  hl=2 l=   9 cons: SEQUENCE
 7455:d=4  hl=2 l=   5 prim: OBJECT            :sha1
 7462:d=4  hl=2 l=   0 prim: NULL
 7464:d=3  hl=2 l=  20 prim: OCTET STRING      [HEX DUMP]:3F7A1617471317C1CC87F78A1C829..
 7486:d=2  hl=2 l=  20 prim: OCTET STRING      [HEX DUMP]:DDEEC4D93B9E95F92DCBEF42C27D7..
 7508:d=2  hl=2 l=   3 prim: INTEGER           :019000
 7513:d=1  hl=2 l=   0 prim: EOC

Second one, working fine:
    0:d=0  hl=4 l=7422 cons: SEQUENCE
    4:d=1  hl=2 l=   1 prim: INTEGER           :03
    7:d=1  hl=4 l=7352 cons: SEQUENCE
   11:d=2  hl=2 l=   9 prim: OBJECT            :pkcs7-data
   22:d=2  hl=4 l=7337 cons: cont [ 0 ]
   26:d=3  hl=4 l=7333 prim: OCTET STRING      [HEX DUMP]:30821CA13082058E06092A864886F70D0...
 7363:d=1  hl=2 l=  61 cons: SEQUENCE
 7365:d=2  hl=2 l=  33 cons: SEQUENCE
 7367:d=3  hl=2 l=   9 cons: SEQUENCE
 7369:d=4  hl=2 l=   5 prim: OBJECT            :sha1
 7376:d=4  hl=2 l=   0 prim: NULL
 7378:d=3  hl=2 l=  20 prim: OCTET STRING      [HEX DUMP]:92BB2DEFD16D48041E1F002959829EF00B4933FF
 7400:d=2  hl=2 l=  20 prim: OCTET STRING      [HEX DUMP]:3770C81500C9513780C1ECE9824F16B52C73DAD5
 7422:d=2  hl=2 l=   2 prim: INTEGER           :0400

**Comment by dainnilsson** [comment]
Ah! It looks like it uses indefinite-length encoding for the TLVs, we should be able to add support for that.
To be continued...

**Comment by glop2801** [comment]
Great !! Many thanks !!
As said previously, i have no issue with version 1.1.5 of the Yubikey manager, may be this could help, or not at all.

**Comment by dainnilsson** [comment]
Could you try the build from here: https://github.com/Yubico/yubikey-manager/actions/runs/835738973 and see if it works with the "non-working" certificates? I believe I have a fix, but of course there could be other issues causing problems here.

**Comment by glop2801** [comment]
Hi Dain,
After some test i can say:
YES , I can import all my certificates (actives, revoked, expired) on slots 9a, 9c , 82, 83 ...

But, i cannot use them. Certificate is accessible but seems the private key is not well formatted.
examples , using :
yubico-piv-tool -aread-cert -s9a
yubico-piv-tool -averify-pin -atest-signature -s9a  , then,  the command never ends.

Sign a PDF file, Adobe can see the certificate , but end with a "internal consistency check failed".

Sign an email or access encrypted emails with outlook , i have the message "Your ID name cannot be found by the underlying security system. 

Again, many many thanks for your help on this .

Best

**Comment by dainnilsson** [comment]
Great, that's good progress! Are you importing the actual key as well? You have to import both the key and certificate for it to work: `ykman piv keys import ...`

**Comment by glop2801** [comment]
Oups, i missed this part, really sorry. 
YES !! All ok  for all certificates with this build !!
ykman-pkcs-12-indeterminate.exe piv certificates import
+
ykman-pkcs-12-indeterminate.exe piv keys import

For each certificates.

All test are OK with  yubico-piv-tool, pdf and outlook !!

Could this be implemented for the next version of Yubikey Manager qt ?
many many thanks

**Comment by fdennis** [comment]
@glop2801 YubiKey Manager Qt 1.2.3 was just released. Can you try installing it and lettings us know if it works as expected?

**Comment by glop2801** [comment]
Wonderful , i try ASAP and let you know

**Comment by glop2801** [comment]
All good !! Many many thanks for issuing this version so fast.
