### ISSUE TITLE
How to create a PIV certificate with require-touch policy?

### ISSUE THREAD

**Issue by wAuner** [Yubico/yubikey-manager-qt#288]
I want to use the yubikey as a smartcard for user authentication for macOS. When I insert the key it automatically prompts me to pair. 
I'd like to configure it in such a waythat it does require a touch, not only the PIN.
I haven't found any option for that in the GUI. I've tried it via terminal with 
* `ykman piv keys generate --touch-policy always 9a pubkey.pem`, followed by
*  `ykman piv certificates generate -s "CN=blub" 9a pubkey.pem`
But this results in this error:
<img width="566" alt="Screenshot 2021-05-19 at 17 39 25" src="https://user-images.githubusercontent.com/18383180/118842182-80d70300-b8b8-11eb-85a7-15f1adf17c3d.png">

How can I do this? Thanks! 
macOS 11.3.1, arm64, YubiKey Manager (ykman) version: 4.0.2

**Comment by fdennis** [comment]
Hey,
The commands look correct and should work. Are you touching the YubiKey when it starts blinking?

**Comment by wAuner** [comment]
Yes I did touch it when I was prompted for it in the terminal.

**Comment by fdennis** [comment]
When you are pairing it you should also, most likely, touch the YubiKey. Have you tried that as well?

**Comment by wAuner** [comment]
ah thanks! that was it. I didn't touch the key during pairing. Is there a suggestion on where to store the pubkey that"s created during the first step? Can I move it around or is it still needed and the path referenced somewhere?

**Comment by fdennis** [comment]
You can move it around and do whatever you want to. It was needed only to generate the cert. If you in the future want to generate a new cert you could use the same pubkey, but you can also extract this pubkey from the cert or just generate a completely new key pair and redo the process you just did.

**Comment by wAuner** [comment]
Thanks a lot! Would be great if it was possible to set the touch policy in the gui in a future version.

**Comment by alfonsrv** [comment]
Is it possible to enable this for an already existing certificate or is this some special policy OID that's baked into the generated cert?
