### ISSUE TITLE
ykman and Freebsd 13

### ISSUE THREAD

**Issue by iandstanley** [Yubico/yubikey-manager-qt#290]
I am trying to get my yubikey 5 working with FreeBSD v13.0 on my laptop
I also have a yubikey 4 and a neo to hand to test as well

Each of these keys work perfectly on my desktop under Debian 10

### INSTALLED SOFTWARE
I have installed the following software from the FreeBSD 13 repositories

- libyubikey, 
- yubico-piv-tool, yubikey-agent, yubikey-manager-qt, yubikey-personalization-gui, pam_yubico
also 
- pcsc-lite, opensc

### First of all ... what works
- I can run ykinfo and pull up all the details from each key I try 
- I have u2f working on firefox and can login with any of my keys into the demo.yubico.com test server.
- ykpersonalisation cli works fine as does the gui

# What fails 
- Oddly FIDO2 under firefox on the demo.yubico.com test server with my yubikey 5nfc (???)
- ykman cli and gui (different errors but may be linked)
- 

## ykman-gui

ian@frodo:~ $ ykman-gui -v
YubiKey Manager 1.2.0

GUI loads fine but ignores any inserted yubikey with the following errors 

`
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: qrc:/qml/YubiKey.qml:205: Error: Cannot assign [undefined] to int

`

## ** ykman cli**

When I run ykman cli I get the following issue:
ian@frodo:~ $ ykman
Traceback (most recent call last):
  File "/usr/local/bin/ykman", line 11, in <module>
    load_entry_point('yubikey-manager==4.0.0', 'console_scripts', 'ykman')()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/site-packages/ykman/__init__.py", line 29, in <module>
    from .device import (  # noqa
  File "/usr/local/lib/python3.7/site-packages/ykman/device.py", line 52, in <module>
    from .hid import list_otp_devices, list_ctap_devices
  File "/usr/local/lib/python3.7/site-packages/ykman/hid/__init__.py", line 46, in <module>
    raise Exception("Unsupported platform")
Exception: Unsupported platform

## yubikey-manager 4.0 is installed
`
 pkg info py37-yubikey-manager
py37-yubikey-manager-4.0.0
Name           : py37-yubikey-manager
Version        : 4.0.0
Installed on   : Wed Jun  9 00:00:25 2021 BST
`

Just a bit lost and confused with this as most things work except ykman/ykman gui 

Any ideas?

**Comment by iandstanley** [comment]
pcscd is running

when i run pcsc_scan I get the following as I insert my yubikey5
`
Using reader plug'n play mechanism
Scanning present readers...
Waiting for the first reader...   ^found one
Scanning present readers...
0: Yubico YubiKey OTP+FIDO+CCID 00 00

Wed Jun  9 00:52:37 2021
 Reader 0: Yubico YubiKey OTP+FIDO+CCID 00 00
  Event number: 0
  Card state: Card inserted,
  ATR: 3B FD 13 00 00 81 31 FE 15 80 73 C0 21 C0 57 59 75 62 69 4B 65 79 40

ATR: 3B FD 13 00 00 81 31 FE 15 80 73 C0 21 C0 57 59 75 62 69 4B 65 79 40
+ TS = 3B --> Direct Convention
+ T0 = FD, Y(1): 1111, K: 13 (historical bytes)
  TA(1) = 13 --> Fi=372, Di=4, 93 cycles/ETU
    43010 bits/s at 4 MHz, fMax for Fi = 5 MHz => 53763 bits/s
  TB(1) = 00 --> VPP is not electrically connected
  TC(1) = 00 --> Extra guard time: 0
  TD(1) = 81 --> Y(i+1) = 1000, Protocol T = 1
-----
  TD(2) = 31 --> Y(i+1) = 0011, Protocol T = 1
-----
  TA(3) = FE --> IFSC: 254
  TB(3) = 15 --> Block Waiting Integer: 1 - Character Waiting Integer: 5
+ Historical bytes: 80 73 C0 21 C0 57 59 75 62 69 4B 65 79
  Category indicator byte: 80 (compact TLV data object)
    Tag: 7, len: 3 (card capabilities)
      Selection methods: C0
        - DF selection by full DF name
        - DF selection by partial DF name
      Data coding byte: 21
        - Behaviour of write functions: proprietary
        - Value 'FF' for the first byte of BER-TLV tag fields: invalid
        - Data unit in quartets: 2
      Command chaining, length fields and logical channels: C0
        - Command chaining
        - Extended Lc and Le fields
        - Logical channel number assignment: No logical channel
        - Maximum number of logical channels: 1
    Tag: 5, len: 7 (card issuer's data)
      Card issuer data: 59 75 62 69 4B 65 79
+ TCK = 40 (correct checksum)

Possibly identified card (using /usr/local/share/pcsc/smartcard_list.txt):
3B FD 13 00 00 81 31 FE 15 80 73 C0 21 C0 57 59 75 62 69 4B 65 79 40
        Yubico YubiKey 5 NFC (PKI)
        https://www.yubico.com/product/yubikey-5-nfc
`

**Comment by dainnilsson** [comment]
In short: ykman CLI and GUI aren't supported on FreeBSD, and currently are not expected to work on this platform.

For ykman CLI we recently made a change (in 4.0.3) which will allow the tool to run for some of the commands (those which use the CCID or FIDO USB transports) but will fail for anything that needs the OTP interface, as there currently is no OTP backend for FreeBSD. This means all commands that don't start with `ykman otp` should most likely work.

The GUI relies on all these transports, so likely will not run at all. Version 1.2.3 of the GUI uses ykman 4.0.3, so that _might_ work for some of the functionality, but this is untested.

To be able to support FreeBSD, the main thing missing is a backend for communicating with the OTP interface, which would need to be added to the ykman project.
