### ISSUE TITLE
Security Key detection change 1.2.3b -> 1.2.4 Linux AppImage

### ISSUE THREAD

**Issue by roycewilliams** [Yubico/yubikey-manager-qt#307]
My Security Key NFC and Security Key C NFC by Yubico (and others - see below) are detected and manageable with yubikey-manager-qt 1.2.3b, but not with 1.2.4, using the Linux AppImage.

1.2.3b sees them without issue, so I presume that it's not a per-key or per-individual-system issue, but just in case:

* OS is Xubuntu 20.04
* Keys still appear properly in Linux dmesg
* Keys still work fine for new WebAuthn registrations, etc
* Keys are confirmed genuine as validated at https://www.yubico.com/genuine/
* Issue persists across a fresh reboot.

Versions of AppImage tested (SHA1s):

72613deeaff327f9d0c7141bcf584e7851d48164  yubikey-manager-qt-1.2.3b-linux.AppImage
78afb37cc46f69335fe293ea9c6e0368634d638c  yubikey-manager-qt-1.2.4-linux.AppImage

Additional key testing:

OK:
* YubiKey Standard (Symantec VIP version)
* YubiKey Plus
* Yubikey 4 (white)
* YubiKey 5 NFC (GitHub branded edition)

Not OK:
* 1st gen blue Security Key by Yubico (non-NFC, as "FIDO U2F Security Key")
* 1st gen black GitHub security key (as "FIDO U2F Security Key")
* 2nd gen blue Security Key by Yubico (non-NFC, as "FIDO U2F Security Key")
* 3rd gen blue Security Key by Yubico (non-NFC, as "Security Key by Yubico") with "2" label
* Security Key NFC
* Security Key C NFC

Theory: something different about "Security Key" as a detection string?

**Comment by fdennis** [comment]
Could you try running with the `--log-level DEBUG` flag with a key that does not work? It might print something useful.

**Comment by roycewilliams** [comment]
Only the initial startup logging - no new output when inserting one of the affected keys:
```
2021-11-01T09:43:21-0800 INFO [ykman.logging_setup.setup:76] Initialized logging for level: DEBUG
2021-11-01T09:43:21-0800 INFO [ykman.logging_setup.setup:77] Running ykman version: 4.0.7
2021-11-01T09:43:21-0800 DEBUG [ykman.logging_setup.log_sys_info:48] Python: 3.8.3 (default, Oct 26 2021, 08:21:49) 
[GCC 5.4.0 20160609]
2021-11-01T09:43:21-0800 DEBUG [ykman.logging_setup.log_sys_info:49] Platform: linux
2021-11-01T09:43:21-0800 DEBUG [ykman.logging_setup.log_sys_info:50] Arch: x86_64
2021-11-01T09:43:21-0800 DEBUG [ykman.logging_setup.log_sys_info:56] Running as admin: False
```

**Comment by roycewilliams** [comment]
Additional data point: someone reported a "no keys at all" version of this issue on Twitter, but I'm unable to replicate that using 1.2.4 on 10.15.17 - both Security Keys and other keys are all properly recognized.

**Comment by MasterKale** [comment]
It's me, I'm the one with v1.2.4 unable to recognize anything. My issue is with macOS, though, so it's probably not worthwhile to troubleshoot that in here. I can make an Issue here, though I already reported it via Yubico's official support channels so maybe I just wait?

**Comment by fdennis** [comment]
@roycewilliams Seems related to https://github.com/Yubico/python-fido2/issues/127

**Comment by fdennis** [comment]
@roycewilliams Could you try 1.2.4b from this page https://developers.yubico.com/yubikey-manager-qt/Releases/ and let me know if it works better?

**Comment by roycewilliams** [comment]
All of my previous failing Security Keys (etc.) are now confirmed to be properly detected in 1.2.4b - thanks!
