### ISSUE TITLE
ykman piv import keys not importing

### ISSUE THREAD

**Issue by im-richard** [Yubico/yubikey-manager-qt#339]
- YubiKey Manager version: 1.2.5
- How was it installed?: setup.exe
- Operating system and version: Windows 11 22H2
- YubiKey model and version: 5 NFC | Firmware 5.4.3
- Bug description summary:

Unable to import keys using using `ykman piv keys import --touch-policy ALWAYS 9e "file.pfx"`
If I load up yubikey manager -> PIV -> Select slot 9E, I can manually import it using Yubikey Manager and it works fine. However, I cannot modify the touch / pin policy that way.

Steps to reproduce
---

Simply import any pfx file into any slot in the PIV module. 
After running piv keys import, it will ask the normal questions such as:

```
Enter password to decrypt key:
Enter a management key [blank to use default key]:
```
No errors appear after that point, it goes back to command prompt like it should. But when opening the Yubikey Manager, there's nothing in there.

Expected result
---

Normally it imports your keys into the desired slot.

Actual results
---

Does nothing. No key imported.

Other info
---

I've used these same exact keys before and they imported fine.
I even started doing dumb tests like using a bad password to see if it was even reading the file, and it appears to be.

[screenshot](https://i.imgur.com/C7uiCtW.png)

**Comment by dainnilsson** [comment]
Glad to hear that it's now working, here's what I think caused this:

In PIV, each slot can hold both a key and a certificate, and they are separate from each other (though the most common use-case is to have matching pairs).

In the YubiKey Manager GUI when you import from a PFX file that contains both a key and a certificate, both of those objects are imported into the YubiKey.

The CLI however, uses more explicit actions where you have to import the two objects independently, using `ykman piv keys import` and `ykman piv certificates import`. My guess is that you imported the key only, and not the certificate.
