### ISSUE TITLE
The GUI application does not work when built from release tarball with python 3.12

### ISSUE THREAD

**Issue by Jakuje** [Yubico/yubikey-manager-qt#357]
- YubiKey Manager version: yubikey-manager-qt-1.2.5
- How was it installed?: RPM package built from official release tarball
- Operating system and version: Fedora
- YubiKey model and version: does not matter
- Bug description summary: The GUI application does not work when built from release tarball

The Fedora packages are not distributed as appimages, but as RPMs, that are built from the official release tarballs provided on https://developers.yubico.com/yubikey-manager-qt/Releases/ The package stopped working with Fedora 39 with exactly same code (likely some dependencies were updated).

The users report that the AppImage still keeps working for them (https://bugzilla.redhat.com/show_bug.cgi?id=2251082) so I wanted to figure out what is a difference in our build from the AppImage from our packages, but so far I noticed only the difference in python version, where Appimage forces 3.11, while Fedora 39 updated to Python 3.12, which might cause some issues with the bindings?

Running with `--log-level DEBUG` does not show any output nor failures.

I am not completely sure about the application architecture to be able to pinpoint the issue, but I suspect it is related to the python version. Is there a way to get some more debug logs or trace logs to see what is failing where?

Steps to reproduce
---
 * Install yubikey-manager-qt package in Fedora and run it

Expected result
---
The application should show connected Yubikeys.

Actual results
---
No buttons are active, the app does not react to any inputs except for Help and About.

![image](https://github.com/Yubico/yubikey-manager-qt/assets/2694489/f8aa7b73-f1b3-482d-9af5-759962746839)

Other info
---
I do not know what more I can provide. Please, let me know what information would be helpful to debug this further.

**Comment by myroslav** [comment]
I do have same behavior.

Can that be connected with `pcscd` from pcsc-lite-2.0.1-1.fc39 that is behaving like in https://discussion.fedoraproject.org/t/fedora-39-unable-to-use-openpgp-smartcard/99672:
* `pcsc_scan` reveals YubiKey
* `gpg --card-status` reports `No such device`

**Comment by Jakuje** [comment]
Thank you for the pointer @Aloxaf ! Filled Fedora bug to get this fixed: https://bugzilla.redhat.com/show_bug.cgi?id=2277686

**Comment by robsdudeson** [comment]
Ran into a similar issue on Manjaro(Arch).  I was able to work around this by installing [python-pyotherside-moment-git](http://aur.archlinux.org/packages/python-pyotherside-moment-git) and then installing [yubikey-manager-qt](https://archlinux.org/packages/extra/x86_64/yubikey-manager-qt/)

**Comment by orjawell** [comment]
Look for this [work-around,](https://github.com/Yubico/yubikey-manager-qt/issues/361#issuecomment-2094872243) it worked well for me !

**Comment by orjawell** [comment]
Can you run this command : ` ykman-gui --log-level DEBUG` and send us the error.

**Comment by uaqben** [comment]
> Can you run this command : ` ykman-gui --log-level DEBUG` and send us the error.

@orjawell There is no error..

![Screenshot from 2024-05-10 13-08-55](https://github.com/Yubico/yubikey-manager-qt/assets/11063165/004f4cf1-6bca-4c4e-9435-1d7be524a2a2)

**Comment by orjawell** [comment]
> > Can you run this command : ` ykman-gui --log-level DEBUG` and send us the error.
> 
> @orjawell There is no error..
> 
> ![Screenshot from 2024-05-10 13-08-55](https://private-user-images.githubusercontent.com/11063165/329559262-004f4cf1-6bca-4c4e-9435-1d7be524a2a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNDI3MjMsIm5iZiI6MTcxNTM0MjQyMywicGF0aCI6Ii8xMTA2MzE2NS8zMjk1NTkyNjItMDA0ZjRjZjEtNmJjYS00YzRlLTk0MzUtMWQ3YmU1MjRhMmEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDEyMDAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmODRlYjgxNjkwZjk5YjNkYzQ3YzdhZjYyMDA0Zjk0ZmI4Y2YzYzAwZGNlYjU3ZGRiNGZjMDY2ZDczZjE2NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ImrY3_MOuoYzmy9WTFkWzxEVB-0DNR-rrowC7vDp_80)

Try [this](https://github.com/Yubico/yubikey-manager-qt/issues/361#issuecomment-2094872243) and redo the same command but with your yubikey inserted

**Comment by leigh123linux** [comment]
Does this update fix the issue for you?

https://bodhi.fedoraproject.org/updates/FEDORA-2024-f563337283

**Comment by rathann** [comment]
> Does this update fix the issue for you?
> 
> https://bodhi.fedoraproject.org/updates/FEDORA-2024-f563337283

It doesn't.

**Comment by leigh123linux** [comment]
> > Does this update fix the issue for you?
> > https://bodhi.fedoraproject.org/updates/FEDORA-2024-f563337283
> 
> It doesn't.

It worked ok when I tested the package but it fails now in the same way,

**Comment by leigh123linux** [comment]
> > Does this update fix the issue for you?
> > https://bodhi.fedoraproject.org/updates/FEDORA-2024-f563337283
> 
> It doesn't.

@rathann  Try downgrading yubikey-manager

```
sudo dnf downgrade python3-yubikey-manager
```

It seems this hit stable after I fixed it https://bodhi.fedoraproject.org/updates/FEDORA-2024-8c7e2799df

**Comment by ricardobranco777** [comment]
> @rathann Try downgrading yubikey-manager
> 
> ```
> sudo dnf downgrade python3-yubikey-manager
> ```

Now it works. I also ran `sudo dnf versionlock add python3-yubikey-manager yubikey-manager` to avoid any unwanted updates.

**Comment by Jakuje** [comment]
This was resolved in Fedora by backporting patches from #363. I updated all Fedoras, but I have only F40, which is where I verified this works:

https://bodhi.fedoraproject.org/updates/FEDORA-2024-7fdb5f56e8

Closing. If the issue persists, please make sure you have the above version and open a new issue.

**Comment by ricardobranco777** [comment]
> This was resolved in Fedora by backporting patches from #363. I updated all Fedoras, but I have only F40, which is where I verified this works:
> 
> https://bodhi.fedoraproject.org/updates/FEDORA-2024-7fdb5f56e8
> 
> Closing. If the issue persists, please make sure you have the above version and open a new issue.

```
QSocketNotifier: Can only be used with threads started with QThread
QQmlApplicationEngine failed to load component
qrc:/qml/main.qml:131:5: Type ContentStack unavailable
qrc:/qml/ContentStack.qml:219:9: Type OtpYubiOtpView unavailable
qrc:/qml/OtpYubiOtpView.qml:160:17: Property value set multiple times
Segmentation fault (core dumped)
```

**Comment by maksimsamt** [comment]
> > This was resolved in Fedora by backporting patches from #363. I updated all Fedoras, but I have only F40, which is where I verified this works:
> > https://bodhi.fedoraproject.org/updates/FEDORA-2024-7fdb5f56e8
> > Closing. If the issue persists, please make sure you have the above version and open a new issue.
> 
> ```
> QSocketNotifier: Can only be used with threads started with QThread
> QQmlApplicationEngine failed to load component
> qrc:/qml/main.qml:131:5: Type ContentStack unavailable
> qrc:/qml/ContentStack.qml:219:9: Type OtpYubiOtpView unavailable
> qrc:/qml/OtpYubiOtpView.qml:160:17: Property value set multiple times
> Segmentation fault (core dumped)
> ```

The same issue on Fedora 40 (Kinoite).
```
rpm -qa yubikey-manager-qt
yubikey-manager-qt-1.2.5-6.fc40.x86_64
```

**Comment by Jakuje** [comment]
Ugh ... wondering what I tested then. Now I can reproduce the issue. Let me have a better look.

**Comment by Jakuje** [comment]
Updating Fedora now with one more change that I reported in #363, which was preventing the GUI to start up. And tested locally that it works ok now.

**Comment by maksimsamt** [comment]
> Updating Fedora now with one more change that I reported in #363, which was preventing the GUI to start up. And tested locally that it works ok now.

Thank you! Now YubiKey Manager (ykman-gui) works in Fedora 40 (with the latest updates)

**Comment by Jakuje** [comment]
Thanks for verifying!
