### ISSUE TITLE
yubikey-manager-qt-0.5.1: tarball is not compressed and contains an incorrect entry

### ISSUE THREAD

**Issue by gktrk** [Yubico/yubikey-manager-qt#49]
The release file [yubikey-manager-qt-0.5.1.tar.gz](https://github.com/Yubico/yubikey-manager-qt/releases/download/yubikey-manager-qt-0.5.1/yubikey-manager-qt-0.5.1.tar.gz) (SHA256 b641c993d37b0e96ec8e543e6c5ce28ecfcfb48d66ef839c9442f942a85bfeb6) doesn't appear to be a gzip compressed data:

```
$ file yubikey-manager-qt-0.5.1.tar.gz 
yubikey-manager-qt-0.5.1.tar.gz: POSIX tar archive
```

Moreover, I get the following error while trying to unpack it:

```
$ tar xvf yubikey-manager-qt-0.5.1.tar.gz 
[...]
tar: .: Cannot utime: Operation not permitted
tar: .: Cannot change mode to rwxr-xr-t: Operation not permitted
tar: Exiting with failure status due to previous errors
```

It works if I try to extract only the `./yubikey-manager-qt` member, i.e. `tar xvf yubikey-manager-qt-0.5.1.tar.gz './yubikey-manager-qt'`. There's a `./` entry in the archive that tries to overwrite the current directory, which fails in my case due to '/tmp' being owned by root:
```
 drwxr-xr-x    user/staff         0 ./
```

**Comment by dagheyman** [comment]
Thanks for reporting this. The problem is that the tar archive is not compressed (and should not be named .gz). tar on macOS actually unpacks this fine anyway. I have updated internal tools to package this properly with git-archive for the upcoming releases.
