### ISSUE TITLE
R6034 - An application has made an attempt to load the C runtime library incorrectly

### ISSUE THREAD

**Issue by yubichris** [Yubico/yubikey-manager-qt#5]
System: Windows 7 Professional SP1 (version 6.1, build 7601, SP1)
Error every time the application is run: 
![1](https://cloud.githubusercontent.com/assets/20120899/22489347/d739902c-e7cb-11e6-89c5-44f2ac353a6f.PNG)

**Comment by dagheyman** [comment]
This has been seen when the user had the 0.1.0 version of the tool installed since before, which caused the wrong DLLs to be loaded. Could you try doing a full uninstall and re-install?

The installer should probably make sure that whatever is in the installation directory before is deleted.

**Comment by yubichris** [comment]
Excellent, you are correct. Uninstalling from Add or Remove Programs and then running the installer again solves the issue.
