### ISSUE TITLE
Detailed build / installation instructions

### ISSUE THREAD

**Issue by eworm-de** [Yubico/yubikey-manager-qt#6]
Currently we have `yubikey-neo-manager` in official Arch Linux repositories, but that is going to be removed due to security issues with webkit. So I would like to replace it with `yubikey-manager-qt` but currently struggling with dependencies, building and installation. Are detailed instructions available?

**Comment by dagheyman** [comment]
You could probably get some clues from the [travis file,](https://github.com/Yubico/yubikey-manager-qt/blob/master/.travis.yml) which uses a [Dockerfile](https://github.com/Yubico/yubikey-manager-qt/blob/master/docker/xenial/Dockerfile) to build a [debian package](https://github.com/Yubico/yubikey-manager-qt/blob/master/debian/control).

Also note that this package `yubikey-manager-qt` depends on the python library `yubikey-manager` found [here](https://github.com/Yubico/yubikey-manager), so you would probably want to build that as well. Feel free to ask if you have any specific questions.

**Comment by eworm-de** [comment]
I think I got it. Thanks!
