### ISSUE TITLE
Feature request (or maybe a new project?)

### ISSUE THREAD

**Issue by fredemmott** [Yubico/yubikey-manager-qt#7]
Could you create a chrome extension for easy support for OATH codes? This should include:
 - support for touch (both using and adding)
 - searching/listing all things
 - pasting directly into selected form field
 - adding from website-rendered QR code

**Comment by emlun** [comment]
Thanks for the suggestion, that's a good idea but nothing we currently plan on doing. It's definitely out of scope for this project, and developing and maintaining it would probably be too much work for us to handle at this time. We would however be happy to assist you or anyone else who wants to try this themselves!
