### ISSUE TITLE
yubikey-manager chocolatey package outdated

### ISSUE THREAD

**Issue by cdevalenceQHR** [Yubico/yubikey-manager-qt#71]
Using chocolatey package manager, the entry for yubikey-manager has the following note:

> NOTE: This is an automatically updated package. If you find it is out of date by more than a week, please contact the maintainer(s) and let them know the package is no longer updating correctly.

However, the package has not been updated since the summer.

https://chocolatey.org/packages/yubikey-manager

Could this be updated please?

**Comment by dagheyman** [comment]
Package seems to be updated! Closing.
