### ISSUE TITLE
Install commands on Ubuntu doesn't work

### ISSUE THREAD

**Issue by mefarazath** [Yubico/yubikey-manager-qt#9]
Tried,

```
sudo apt-add-repository ppa:yubico/stable
sudo apt update
sudo apt install yubikey-manager-qt
```

And ended up with

>  E: Unable to locate package yubikey-manager-qt

Am I missing anything?

I understand that there is a note in the README

> This project is in BETA. Any part of the application may change before the next release, and some functionality and documentation are missing at this point.

But installing the manager is something basic and should not be broken. Moreover, until this version is stable we shouldn't deprecate the old [manager ](https://github.com/Yubico/yubikey-neo-manager) either until we have a stable release. Otherwise its a bit misleading for a new user like me :disappointed: .

I ended up installing the deprecated manager and getting my stuff done

**Comment by mefarazath** [comment]
Digged a bit around the repo and found https://github.com/Yubico/yubikey-manager-qt/blob/master/doc/development.adoc

I guess adding a link to the above would be better until the release is stable :smile:

**Comment by dagheyman** [comment]
Thanks for the report. I agree that it is a bit confusing. I think the issue here is that we don't provide packages for Ubuntu 14.04, it should probably be documented better.

**Comment by mefarazath** [comment]
I would like to help to get these packages published... Let me how I can help out?
